// Code generated by "stringer -type=Database -linecomment -output=database_string.go"; DO NOT EDIT.

package icloud

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Public-1]
	_ = x[Private-2]
	_ = x[Shared-3]
}

const _Database_name = "publicprivateshared"

var _Database_index = [...]uint8{0, 6, 13, 19}

func (i Database) String() string {
	i -= 1
	if i >= Database(len(_Database_index)-1) {
		return "Database(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Database_name[_Database_index[i]:_Database_index[i+1]]
}
