// Code generated by "stringer -type=ErrorCode -linecomment -output=error_string.go"; DO NOT EDIT.

package icloud

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unknown-0]
	_ = x[AccessDenied-1]
	_ = x[AtomicError-2]
	_ = x[AuthenticationFailed-3]
	_ = x[AuthenticationRequired-4]
	_ = x[BadRequest-5]
	_ = x[Conflict-6]
	_ = x[Exists-7]
	_ = x[InternalError-8]
	_ = x[NotFound-9]
	_ = x[QuotaExceeded-10]
	_ = x[Throttled-11]
	_ = x[TryAgainLater-12]
	_ = x[ValidatingReferenceError-13]
	_ = x[ZoneNotFound-14]
}

const _ErrorCode_name = "UNKNOWNACCESS_DENIEDATOMIC_ERRORAUTHENTICATION_FAILEDAUTHENTICATION_REQUIREDBAD_REQUESTCONFLICTEXISTSINTERNAL_ERRORNOT_FOUNDQUOTA_EXCEEDEDTHROTTLEDTRY_AGAIN_LATERVALIDATING_REFERENCE_ERRORZONE_NOT_FOUND"

var _ErrorCode_index = [...]uint8{0, 7, 20, 32, 53, 76, 87, 95, 101, 115, 124, 138, 147, 162, 188, 202}

func (i ErrorCode) String() string {
	if i >= ErrorCode(len(_ErrorCode_index)-1) {
		return "ErrorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ErrorCode_name[_ErrorCode_index[i]:_ErrorCode_index[i+1]]
}
